name: Bug report
description: Create a bug report to help us address errors in the repository
title: "[BUG] <bug description>"
labels: [bug]
assignees: shuklaritvik06
body:
  - type: markdown
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
      Thanks for taking the time to fill out this bug! If you need real time help please use discussions.
  - type: input
    id: bugdescription
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false

