name: Ideas
description: Have a new idea or feature request
title: "[FEATURE REQUEST] <description here>"
labels: [enhancement]
body:
  - type: input
    id: description
    attributes:
      label: Description of the idea
      placeholder: "What is your idea?"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the fidea here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CURAJ-Open-Source-Community/Support/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
 
